Cite: 
Cotutor: Ana Rubio Ruiz
Csl: input/resources/csl/acm-sig-proceedings.csl
Department: Tecnologías y Sistemas de Información
Language: spanish
Month: Julio
Name: Rubén Gómez Villegas
Technology: Sistemas de Información
Title: Protocolo de mensajería ligero inspirado en MQTT para redes ESP-NOW
Subtitle: MQTT-inspired lightweight messaging protocol for ESP-NOW networks
Tutor: Rubén Cantarero Navarro
Year: 2024
