name: Build TFG PDF

on:
  push:
    paths:
      - 'tfg_report/templateAPP/input/**'
  pull_request:
    paths:
      - 'tfg_report/templateAPP/input/**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

#    - name: Log in to Docker Hub
#      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t felix.albertos/tfgii .

    - name: Remove existing Docker container
      run: |
        if [ "$(docker ps -aq -f name=tfgii)" ]; then
          docker rm -f tfgii
        fi

    - name: Run Docker container
      run: docker run -v ${{ github.workspace }}/tfg_report/templateAPP:/home/tfgii/templateAPP --name tfgii felix.albertos/tfgii
